### ISSUE TITLE
unable to install dlib

### ISSUE THREAD

**Issue by ravitejasunkara** [mohith7548/AI_EVM#1]
i have install all dependencies but code is not working reason so can help me to install dlib

**Comment by Nikita1517** [comment]
I'm facing problem in installing dlib. Could you please help me out from this problem.

**Comment by mohith7548** [comment]
Hi, you can install `dlib` on win10, if you have build tools installed. 

If you don't have build tools, you can download the wheel file from [here](https://pypi.org/simple/dlib/).
I suggest to use Python3.6 & download `dlib-19.8.1-cp36-cp36m-win_amd64.whl` file to install.

If you're on Linux/Mac installing `dlib` should be easier.

**Comment by Nikita1517** [comment]
Thanks,
Now everything is working properly. One more problem which I'm facing is regarding name.
In face recognition step (third step), it is not showing my name, even I have changed data in database. It is showing pooja, Mohit.... 
I tried to change name in dataset_faces.dat file, but it showing error.
I tried to open dataset_faces.dat but can't open.

**Comment by mohith7548** [comment]
Please refer to the Note section in the readme & follow the steps.
We used the `face_recognition` package for face recognition. Refer to that docs for more details.
Run `models/src/Face_Recognition/face.py` file to generate `dataset_faces.dat` & `name_faces.dat` files and put inside `models/recognize_face_models`.
Before running make sure you have all users' pictures inside `faces/user1` `faces/user2` like that. So, the same names would be used.
