### ISSUE TITLE
problem with recognitioin of our name in recognition of face

### ISSUE THREAD

**Issue by ravitejasunkara** [mohith7548/AI_EVM#2]
after executing the project in third step recognition of face it's showing name pooja or venkatesh or other names for my face not showing my name even after chnaging the names in the database and we can't open dataset_faces.dat file so please help me to get out of this problem

**Comment by mohith7548** [comment]
Please refer to the Note section in the readme & follow the steps.
We used the `face_recognition` package for face recognition. Refer to that docs for more details.
Run `models/src/Face_Recognition/face.py` file to generate `dataset_faces.dat` & `name_faces.dat` files and put inside `models/recognize_face_models`.
Before running make sure you have all users' pictures inside `faces/user1` `faces/user2` like that. So, the same names would be used.

**Comment by hemantyadav9810** [comment]
i haad created a folder name faces and in that added the pictures of all users but when i run the file face.py its generate the two files but both are empty .
